CREATE TABLE pets (
  pet_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  pet_name VARCHAR(32) NOT NULL,
  pet_status INT NOT NULL DEFAULT 1,
  pet_store INT,
  pet_image BYTEA,
  removed_at TIMESTAMPTZ
);

CREATE TABLE pet_statuses (
  pet_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  pet_status_name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE stores (
  store_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  store_name VARCHAR(64) NOT NULL,
  decommissioned_at TIMESTAMPTZ
);

CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_name VARCHAR(16) UNIQUE NOT NULL,
  user_email VARCHAR(128) UNIQUE NOT NULL,
  deactivated_at TIMESTAMPTZ
);

CREATE TABLE orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  pet_id INT NOT NULL,
  order_status INT NOT NULL DEFAULT 1
);

CREATE TABLE order_statuses (
  order_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  order_status_name VARCHAR(16) UNIQUE NOT NULL
);

ALTER TABLE pets ADD FOREIGN KEY (pet_status) REFERENCES pet_statuses (pet_status_id);

ALTER TABLE pets ADD FOREIGN KEY (pet_store) REFERENCES stores (store_id);

ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE orders ADD FOREIGN KEY (pet_id) REFERENCES pets (pet_id);

ALTER TABLE orders ADD FOREIGN KEY (order_status) REFERENCES order_statuses (order_status_id);
